name: Daily Lighthouse Test

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://www.benu.ch
          temporaryPublicStorage: true
